### ISSUE TITLE
Running :Cljfmt clears current buffer.

### ISSUE THREAD

**Issue by zachbai** [venantius/vim-cljfmt#48]
:Cljfmt clears the entire buffer contents, no matter the expression.  No error message is shown. 

Using Vim 8.1, installed vim-fireplace today as well at commit 237c122. Tried using the most recent cljfmt release, 0.6.8, as well as 0.5.1, which is used in the installation instructions.

The relevant section of my ~/.lein/profiles.clj:

```
:plugins [[cider/cider-nrepl "0.25.2"]]
:dependencies [[cljfmt "0.5.1"]]
:repl-options {:init (require 'cljfmt.core)}
```

Seems like this could possibly be the same issue as #15, though that was filed over 5 years ago. Happy to provide any more information that might be helpful with repro or debugging.

**Comment by venantius** [comment]
This is somehow related to Fireplace. I had an old version of Fireplace (was on 63d7209) working fine and just updated it to 237c122 and am now getting the same behavior as you. I'm not actively developing these days so I'm afraid I don't have the time to chase down the precise cause but that should give you a strong enough breadcrumb to be worth pursuing.

**Comment by zachbai** [comment]
Ah I see. Thanks for the pointer, glad the issue isn't unique to me.

**Comment by raycheung** [comment]
I tried to play around reverting a few commits in vim-fireplace, found this issue appeared since https://github.com/tpope/vim-fireplace/commit/f633ed9b374b46631f277aaf1e3bf7c1bacf485a, which is similar to https://github.com/tpope/vim-fireplace/issues/378 in some way.

Try to use vim-cljfmt, with vim-fireplace prior to that commit, it works perfectly.

**Comment by sushovannits** [comment]
Thanks @raycheung !!

**Comment by tpope** [comment]
tpope/vim-fireplace#378 is now fixed.

**Comment by zachschultz** [comment]
I'm still having this issue on the latest `vim-fireplace` and `vim-cljfmt`. Formatting works as expected on `vim-fireplace` commit: `8a4f232e9844d73adb41eb29148f0c046c730f98`

**Comment by jeremyvdw** [comment]
I had the same issue, reverting vim-fireplace to commit `8a4f232e9844d73adb41eb29148f0c046c730f98` like @zachschultz mentioned does the trick.

**Comment by nezaj** [comment]
+1 to this issue -- was also able to resolve by reverting to `8a4f232e9844d73adb41eb29148f0c046c730f98`

**Comment by andrew-t-james-hm** [comment]
+1 to this issue still blowing away the current buffer.

**Comment by tpope** [comment]
Replace the `redir` shenanigans with something like `let l:result = fireplace#clj().Eval(...).out`.

**Comment by jsn** [comment]
#49 here's a pull request that fixes this.

**Comment by tpope** [comment]
Make sure you verify the error handling still works and the empty buffer edge case.

**Comment by jsn** [comment]
> Make sure you verify the error handling still works and the empty buffer edge case.

Thank you for those hints! Unfortunately I don't really know any vimscript and don't have time to learn any of it now. I tried to figure out what you mean to the best of my ability and came up with this patch by randomly trying things https://github.com/jsn/vim-cljfmt/commit/05a2920ae6f0ae9876d61b16043e4658bf6eaed3 . If you find time to take a look and if you think it's a step in the right direction, I'll submit it in another pull request, If not -- well, hopefully someone with a knowledge of vimscript and free time will stumble upon it sometime later.

**Comment by jeremyvdw** [comment]
Thanks @tpope @jsn to have taken care of this.
